---
# This role installs Docker for centos 8 and enables it on boot

  # Make sure we have the latest yum utils version
  - name: Install required packages
    become: true
    yum:
      name: 
        - yum-utils
        - python3
        - python3-pip
      state: latest

  # Adds the docker-ce repository to the machine
  - name: creating a docker repository
    become: true
    yum_repository:
      description: repo for docker
      name: docker-ce
      baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
      gpgkey: https://download.docker.com/linux/centos/gpg
      gpgcheck: yes

  # Installs docker on the machine
  - name: install docker-ce
    become: true
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
  # Retrieves the docker version
  - name: get docker version
    become: true
    shell: "docker -v"
    register: version

  # Prints out the installed docker version
  - debug: var=version.stdout
  
  # Starts the docker service and enables docker on boot
  - name: Start Docker service
    become: true
    service:
      name: docker
      state: started
      enabled: yes

  # Install the Docker SDK module      
  - name: Install Docker SDK
    become: true
    pip:
      name: docker
...
